name: run-ci

on: pull_request

# This job installs dependencies and run tox
jobs:
  test-book:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Install and setup platform
      - name: Set up Python 3.10
        uses: actions/setup-python@v1
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install -U pip setuptools
          pip install -r requirements.txt
          pip install tox

      # Run TOX
      - name: Build and check
        run: |
          tox

